### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by mergilmartin** [gigapixel/atom-language-gherkin#6]
Atom now shows a deprecated call error when using this package. 

Details: 

Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (C:\Users\user\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:565:9)
<unknown> (C:\Users\user\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:187:43)
```

Let me know if you need extra information

**Comment by gigapixel** [comment]
Fixed in v1.0.2 please check.
