### ISSUE TITLE
Missing tag feature color 

### ISSUE THREAD

**Issue by Spy-Seth** [gigapixel/atom-language-gherkin#8]
The Gherkin allow to put tag on a feature, but for now we do not have syntax highlight: 

![capture d ecran 2015-07-20 a 10 45 21](https://cloud.githubusercontent.com/assets/95120/8772456/a261331e-2ecc-11e5-90dd-7a288646573b.png)

Could you add it?

**Comment by gigapixel** [comment]
Fixed on v1.0.3 please check.

**Comment by Spy-Seth** [comment]
It's good :+1:
